services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    env_file: ".env"
    volumes:
      - embedding_db:/app/embedding_db  
      - model_cache:/app/embedding_models
    environment:
      - CI_TEST=${CI_TEST}
    depends_on:
      database:
        condition: service_started
      doc_embedding:
        condition: service_completed_successfully
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  database:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db
      - database:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file: ".env"
  doc_embedding:
    build:
      context: .
      dockerfile: ./doc_embedding/Dockerfile
    command: python embed_documents.py
    restart: "no"
    volumes:
      - embedding_db:/app/embedding_db
      - model_cache:/app/embedding_models
    environment:
      - CI_TEST=${CI_TEST}
volumes:
  database:
  embedding_db:
  model_cache: