services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: ".env"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  database:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db
      - database:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file: ".env"
volumes:
  database: