name: Test Backend

on:
  push:
    branches: [ "main", "staging", "pytest" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Up Docker
       uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: "./docker-compose.yml"
          services: |
            database
            backend
    - name: Install Pytest
      run: docker-compose exec backend pip install pytest==8.3.5
    - name: Backend Tests
      run: docker-compose exec backend pytest tests
